audio_group_load(audio_sfx)
audio_group_load(audio_mu)
audio_play_sound(mu_disclaimer,1,1)
ini_open("savedata.lmao")
globalvar sfx_vol; sfx_vol = ini_read_real("settings","sfx_vol",0.2)
globalvar mu_vol; mu_vol = ini_read_real("settings","mu_vol",0.5)
audio_group_set_gain(audio_mu,mu_vol,0)
audio_group_set_gain(audio_sfx,sfx_vol,0)
if ini_read_real("settings","fullscreen",1)
	window_set_fullscreen(1)
ini_close()